
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: <%= ENV['DB_URL_DEVELOPMENT']%>

test:
  <<: *default
  url: <%= ENV['DB_URL_TEST']%>

production:
  <<: *default
  url: <%= ENV['DB_URL_PRODUCTION']%>
